name: Build and release

on: pull_request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Make garage
        run: yarn get-garage

      - name: Make envfile
        uses: ozaytsev86/create-env-file@v1
        with:
          file-name: './hawk.garage/.env'
          ENV_VUE_APP_API_ENDPOINT: ${{ secrets.VUE_APP_API_ENDPOINT }}
          ENV_VUE_APP_HAWK_TOKEN: ${{ secrets.VUE_APP_HAWK_TOKEN }}
          ENV_VUE_APP_CLOUDPAYMENTS_PUBLIC_ID: ${{ secrets.VUE_APP_CLOUDPAYMENTS_PUBLIC_ID }}

      - run: ls -la
      - run: cat ./hawk.garage/.env
